clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly
options:
  max-time: 60
  docker: true

image: alpinelinux/docker-compose

definitions:
  steps:
    - step: &sonar
        name: Sonar
        script:
          - pipe: sonarsource/sonarcloud-scan:1.2.2
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN}
    - step: &test
        name: Unit Tests
        script:
          - docker-compose up
          - docker-compose run coverage run -m unittest discover test/ --verbose
pipelines:
  default:
    - step: *test