version: "3.8"

services:
  code-scout-python:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_REGION: $AWS_REGION
        AIMEDIC_GROUPER_VERSION: $AIMEDIC_GROUPER_VERSION

#    command: >
#       sh -c "
#        mv /tmp/jars/aimedic-grouper-assembly.jar /home/jovyan/work/resources/jars &&
#        '/usr/local/bin/start.sh' jupyter lab --ServerApp.token=''"
