version: "3.8"

services:
  jupyter_notebook:
    image: jupyter/datascience-notebook:aarch64-lab-3.4.7
    volumes:
      - type: bind
        source: "${PWD}"
        target: /home/jovyan/work
    ports:
      - "8888:8888"
    working_dir: "/home/jovyan/work"
